<div class="btn-group" data-toggle="buttons-checkbox"
	style="margin-top: 5px; margin-bottom: 10px;">
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="0">A</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="1">B</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="2">C</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="3">D</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="4">E</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="5">F</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="6">G</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="7">H</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="8">I</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="9">J</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="10">K</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="11">L</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="12">M</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="13">N</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="14">O</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="15">P</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="16">Q</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="17">R</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="18">S</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="19">T</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="20">U</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="21">V</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="22">W</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="23">X</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="24">Y</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="25">Z</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="26">0</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="27">1</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="28">2</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="29">3</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="30">4</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="31">5</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="32">6</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="33">7</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="34">8</div>
	<div class="btn btn-default alphabet-filter btn-xs"
		data-filter-index="35">9</div>
</div>